### ISSUE TITLE
Bugs when saving as gp5

### ISSUE THREAD

**Issue by buryoutougen** [helge17/tuxguitar#109]
When you save a file as gp5:

- key signatures are not saved
- pinch harmonics get converted to natural harmonics, even on frets where NHs are not available, in which case it will sound like the original note

This is not related to 1.6.0 by the way, these bugs were there forever.

Also a small suggestion, when copying bars, can you add an option to have "all tracks" unchecked by default? Most of the time, I copy a single track and having to uncheck that every time is so annoying.

**Comment by guiv42** [comment]
Thanks for filing this issue. Two different problems here.
1. save as gp5: just a few questions
how does .gp5 file **import** handle the key signatures and pinch harmonics?
Could you please provide a .gp5 file, ideally with 2 different key signatures in different measures ? (I don't have access to GuitarPro)

2. copy "all tracks"
I'm definitely not a big fan of adding options everywhere. Another (simpler) possibility could be to memorize the checkbox state when you close the "copy measures" dialog, for next time. So you would only need to uncheck the option once. What do you think?
By the way, if you usually copy only 1 track , the click&drag feature added in 1.6.0 could help: click in first beat of first measure, shift+click in last beat of last measure, hit Ctrl-C and that's it, you're ready to paste the selected interval (1 track)

**Comment by buryoutougen** [comment]
1. Importing key signatures and pinch harmonics from gp5 files works correctly. I attached 2 tabs, one has the key signature of C minor (3 flats), the other has pinch harmonics (Glenn Tipton track, bar 82). Sorry, I couldn't find a file with 2 different key signatures. 
If you save those files in TuxGuitar, even without doing any changes, the key signature and pinch harmonics will be lost.
2. Remembering the checkbox state would be fine for me. Thanks for letting me know about the new select and copy feature.

[gp5-tabs.zip](https://github.com/helge17/tuxguitar/files/12693677/gp5-tabs.zip)

**Comment by guiv42** [comment]
1. Thank you for the data. It's very good news the import works correctly. I've never looked at that code so it might take some time, but I'm quite confident it can be fixed.
2. OK, fine. I'm currently working on that dialog for another feature, this should be straightforward

I will keep you informed of the progress in this thread

**Comment by guiv42** [comment]
update:
1. keySignature was added by @harborsiem, also in other .gp formats
still need to have a look at the pinch harmonics
2. checkboxes states are now memorized (2 checkboxes now, 1 was added to enable markers copy)

**Comment by guiv42** [comment]
Not so easy, the detailed description of harmonics in gp5 format.
The problem is I cannot find any description of this binary (proprietary) format. And to be honest, I'm also missing the musical theory of harmonics, so I do not understand everything!

**Import** from gp5 file is not exhaustive and only reads harmonic *type*: *natural, artificial, tapped, pinch, semi*. But types *artificial* and *tapped* also include attributes that TuxGuitar ignores. I don't know how these attributes are coded, and if I write arbitrary values when saving, I cannot anticipate how GuitarPro will interpret them.
This absence of information might explain why TuxGuitar currently exports all harmonics as *natural*: no attribute is required in file in this case, so there is no risk to write something inconsistent.

What I should be able to do now:
- export correctly all harmonic types without attributes: *natural, pinch, semi*
- export *artificial* and *tapped* either as *natural, pinch* or *semi*

I don't know what's best. Exporting *artificial* as *natural* can create illegal harmonics.
@buryoutougen: would an export as *pinch* be acceptable?

To go any further I definitely need help. If someone has access to GuitarPro, I would appreciate a gp5 file containing notes with all possible harmonic types and attributes, and a textual description of this file (so I know what harmonic is where). This way I could analyze manually the binary.

**Comment by guiv42** [comment]
I found something (unofficial) [here](https://github.com/Perlence/PyGuitarPro), and the mapping between TuxGuitar and gp5 format is not trivial.

For *artificial*:
- gp5 defines 3 attributes *Note, Accidental, Octave* (however I don't know how they are coded...)
- TuxGuitar defines 6 possible configurations: AH12, AH9, AH5, AH7, AH4, AH3

For *tapped*:
- gp5 defines 1 attribute *Fret*
- TuxGuitar defines the same 6 possible configurations

Could someone help me build a correspondence table between these formats?

**Comment by harborsiem** [comment]
![GuitarPro5](https://github.com/helge17/tuxguitar/assets/28147549/a8331436-2775-4d6e-8d66-a2fc6e3a7dfd)
[Harmonics.zip](https://github.com/helge17/tuxguitar/files/12706924/Harmonics.zip)
Maybe I can help for the harmonics, because I have a  Guitar Pro 5 licence.
The picture shows how one can use the artificial harmonics. The natural harmonics does not have a dialog. Inside Harmonics.zip is the Harmonics.gp5 with content of the picture. 1. note is a natural harmonic, 2. note is a AH, 3. note is a Tapped harmonic, 4. note is a Pinch harmonic, 5. note is a Semi harmonic. Others are normal notes.

**Comment by guiv42** [comment]
Thanks @harborsiem for this example. In the file, the harmonics attributes are:
- *natural, pinch, semi*: no attribute, as expected
- *artificial harmonic*: note=0, accidental=0, octave=0
I don't know precisely what it means, but at least setting these 3 values to zero is something valid for GuitarPro, it's safe to use them, and still better than actual behavior (which converts *artificial* to *natural*). That seems fine.
- *tapped harmonic": fret=6, I guess this correspond to the "right hand" value in drop-down list. It seems more understandable to me, but there is definitely no such correspondence in TuxGuitar note's properties.
Anyone knowing harmonics better than me could suggest which value to set when saving a file?

**Comment by guiv42** [comment]
That's fun, it's the first time I need to take my guitar to better understand the code :)
From what I could find about tapped harmonics, I don't really understand the example in the Harmonics.gp5 file above: left hand on fret 5, right hand on fret 6, how could this produce a harmonic? It would make sense to have left hand on fret 5, and right hand for example on fret (5+7)=12. I assume this corresponds to what TuxGuitar would call a "tapped harmonic T.H(7)".
@harborsiem : could you please try to open the attached gp5 file with GuitarPro? I created this file with a modified TuxGuitar. Five first notes should be similar to your original file. The very last note is a T.H(7) on fret 5. I expect GuitarPro to interpret it as a *tapped harmonic*, with *left hand* on fret 5, and *right hand* attribute set to fret 12.

[Harmonics (1).zip](https://github.com/helge17/tuxguitar/files/12708452/Harmonics.1.zip)

**Comment by buryoutougen** [comment]
To be honest, those Guitar Pro 5 options don't make any sense to me.

My understanding is the same as @guiv42 's. If you play a note on fret 5, you should have tapped harmonics available over frets 17 (5 + 12), 12 (5 + 7), 10 (5 + 5) etc. The same should apply to artificial harmonics. This is reflected by the TuxGuitar options.

It would be interesting to know how Guitar Pro 5 plays tapped harmonics when you select an "incorrect" fret.

**Comment by harborsiem** [comment]
GuitarPro5 opens the attached file correctly. @guiv42 You are right with the very last note.

![Harmonics1](https://github.com/helge17/tuxguitar/assets/28147549/bda08cdd-fc46-411a-996b-ddb1d190b1ee)

**Comment by guiv42** [comment]
OK, thank you both for your feedback. So I'll send a new pull request with this feature

**Comment by guiv42** [comment]
@buryoutougen : don't hesitate to provide feedback when you can test it (either you can build from source right now, or just wait for the next pre-release).
You can also re-open this issue if you think it does not work as expected

**Comment by buryoutougen** [comment]
OK, I think I'll wait for the pre-release.
Thanks for taking the time to fix this.

**Comment by guiv42** [comment]
These features are now available for test, from [pre-release](https://github.com/helge17/tuxguitar/releases) 2023-09-25-snapshot.
And don't hesitate to star this repo if you like it ;)

**Comment by buryoutougen** [comment]
I downloaded the pre-release, the new features appear to work correctly. I also installed the trial version of Guitar Pro 8 and played around with it a little. Some things that I noticed (not problems, just observations):

- In Guitar Pro (both .gp5 and the current .gp format), key signatures apply to all tracks, while in TuxGuitar it's possible to set different keys in different tracks at the same time (I can't see why would you want to do that though). When exporting to .gp5 from TuxGuitar, key signatures from the first track will be saved, and those from the other tracks will be ignored.
- In Guitar Pro 8, harmonics: _artifical, pinch, tapped, semi_, and an additional type _feedback_ all have identical dialog options, mostly corresponding to the TuxGuitar options, except there are 2 more higher harmonics available and you can specify different right hand positions for the selected harmonic (in TuxGuitar there is one example of that - harmonics 4 and 9 produce the same pitch).
- Like you said, in the .gp5 format _pinch_ harmonics don't have attributes. When you import them to TuxGuitar or Guitar Pro 8, they default to the harmonic an octave higher (12).
- Importing _pinch_ and _artificial_ harmonics from .gp in TuxGuitar works correctly if their attributes are within TuxGuitar possible options. Importing _tapped_ and _semi_ from .gp doesn't work.
