### ISSUE TITLE
cannot manage 8string

### ISSUE THREAD

**Issue by aliceinwire** [helge17/tuxguitar#168]
looks like tuxguitar cannot manage 8string tabs as each time I add 8string it keeps adding only 7string
looks like it happens only with guitar pro format

**Comment by guiv42** [comment]
Not sure to understand.
Test done with TuxGuitar 1.6.0:
- create new song
- double click on track, tuning dialog opens
- change tuning, select an 8-string guitar, then click OK to close dialog
- add some notes in the tab
- save file *under .tg format*
- close and re-open file: the 8 strings are there

Whenever you work with TuxGuitar, always use TuxGuitar native file format. When you import a guitar pro tab, save it under .tg format before editing it.
The problem with Guitar Pro file formats is they are *proprietary* formats (i.e. *closed*), so it's very difficult to ensure full compatibility.

**Comment by aliceinwire** [comment]
happen only when saving in a guitar pro tab format, the 8 string is not saved in such format.
I understand that Guitar Pro file format are proprietary.

**Comment by guiv42** [comment]
Okay, I checked with .gp3, .gp4 and .gp5 and I confirm the behavior.
But I don't have a GuitarPro license, so I cannot know if this is a TuxGuitar limitation, or possible a limitation of the GuitarPro file formats themselves.
Help needed: could someone with a GuitarPro license create an 8-string song, save it under .gp3/.gp4/.gp5 formats, and re-open them to check it works correctly? If so, then post here a zip archive with the 3 files.
@aliceinwire: anyway, the most robust solution to your problem is quite straightforward. **Always** "Save As" your tabs under **.tg** format before editing them.

**Comment by helge17** [comment]
The attached files are saved/exported with GuitarPro 6. GP6 cannot export files in gp3 and gp4 format.

This happens when you (re-)open them:

          with GP6                    with TG 2023-12-10
    gpx   OK                          OK
    gp5   Error loading               TG hangs
    mid   6 strings                   6 strings
    xml   8 strings, but no notes     unsupported

So if you want to use your files with GuitarPro, you should use the gpx format.

![grafik](https://github.com/helge17/tuxguitar/assets/5897631/c7c01367-5996-493c-ace0-ec276c6e042d)

[GP6_Test_TG_issue_168_-_8_string.zip](https://github.com/helge17/tuxguitar/files/13640306/GP6_Test_TG_issue_168_-_8_string.zip)
