### ISSUE TITLE
macosx jfx cocoa dropdown menu broken

### ISSUE THREAD

**Issue by belfie13** [helge17/tuxguitar#213]
iMac macOS Monterey v12.7.2

tuxguitar-2024-01-13-snapshot-macosx-jfx-cocoa-x86_64.app

talking about the main app menu (file, edit,...) menu drops down in the middle of the screen and dissappears on mouse up.

it's impossible to use,

1. you have to hold the mouse down to show the menu.

2. the menu is in the middle of the screen (not at the top like where the dropdown should be) so i can't hold the mouse down and drag to the menu item.

**Comment by belfie13** [comment]
also the app icon doesn't load in the macos dock, app is running in a window by itself

**Comment by G-eos** [comment]
Hi there, tuxguitar-1.6.1-macosx-swt-cocoa-x86_64 on Ventura 13.6.1 seems to not have this trouble.
App icon seem son too.

![image](https://github.com/helge17/tuxguitar/assets/1248414/3795e942-0430-45c6-b976-2e293a049cc1)

**Comment by guiv42** [comment]
Yep, that's a JFX-specific issue, as mentioned in original description ;)
TuxGuitar desktop **snapshot** versions are delivered with both SWT and JFX ui frameworks. However, the status of JFX variant is not crystal clear now. It has several issues, but since only the SWT variant is delivered in **releases** these issues are managed with lowest possible priority.
So if you would like to work with latest snapshot I recommend using SWT variant.

**Comment by guiv42** [comment]
my interpretation: I don't think menu integration is *broken* in JFX configuration, it just seems it has *not been developed* yet.
SWT configuration includes a dedicated module "TuxGuitar-cocoa-integration-swt", implementing a [MacMenuPlugin](https://github.com/helge17/tuxguitar/blob/master/desktop/TuxGuitar-cocoa-integration-swt/src/org/herac/tuxguitar/cocoa/menu/MacMenuPlugin.java). But there's no such thing available in JFX config.

**Comment by belfie13** [comment]
1.6.4 Works on my machine, menu is integrated with the system! Nice work!
tuxguitar-1.6.4-macosx-swt-cocoa-x86_64

**Comment by guiv42** [comment]
@belfie13 : according to your last message you tested the **SWT** configuration. But this issue was created for **JFX** configuration, which is only included in pre-releases (so, not in 1.6.4)
Could you please check on [last pre-release of JFX version for mac](https://github.com/helge17/tuxguitar/releases/download/2024-11-07-master/tuxguitar-2024-11-07-master-macosx-jfx-cocoa-x86_64.app.tar.gz), and either confirm issue is solved or re-open it?

**Comment by belfie13** [comment]
oh yes of course i missed that sorry
