### ISSUE TITLE
copy/paste doesn't copy any note or pitch data

### ISSUE THREAD

**Issue by belfie13** [helge17/tuxguitar#218]
copy paste just works on the numbers on the tab, not the notes.

so when pasting into a different tuning, the frets stay the same which means the data wasnt copied at all and the result could be way off.

in any case, the only way copy/paste works is when its between two identical tunings

**Comment by guiv42** [comment]
Confirmed, there is clearly an issue with copy-paste. See video below: 1st track is a standard tuned guitar, 2nd is a dropped-d guitar, 3rd is a standard tuned bass.
First measure is copy-pasted to tracks 2 and 3 with "copy/paste measure" feature: in track 2 one note is changed to keep fret number, in track 3 notes are lost (bug already present in 1.5.6)
Second measure is copy-pasted with "copy/paste selection": same behavior in track 2, and in track 3 this crashes app (bug present since 1.6.0)

https://github.com/helge17/tuxguitar/assets/129443524/db0bccf3-a6c9-463a-bacc-1278f2f4dffa

**Comment by guiv42** [comment]
This is definitely *not* a simple issue.
Looking at the code, I confirm that what gets pasted at the end is a list of tuples (string number, fret number).

I just merged a workaround to avoid the permanent error message shown at the end of video above. Still the main problem persists: pasting to a track with another tuning changes notes.

Copy/Paste feature shall be reworked globally. And notes re-allocated to strings when needed.
#209 also describes an issue when importing midi file + another issue when changing tuning. In these 2 cases, just as in this issue here, there is a need to (re)-allocate a list of notes to a list of strings.
A centralized feature should be implemented to perform this allocation. And then this feature should be called when pasting, when importing a file with no strings/frets defined, when changing tuning, etc.

Quite a complex evolution, this should take some time.

**Comment by guiv42** [comment]
copy-paste from a drums track to a guitar track also produces funny results!

**Comment by guiv42** [comment]
Should be fixed by #238 
As this is quite a complex evolution, some additional testing would be appreciated (regression is still possible).

Modified features:
- copy/paste selection
- copy/paste measure(s), single track
- copy/paste measure(s), all tracks
- midi file import

**Comment by guiv42** [comment]
@belfie13 : can we close this issue now?

**Comment by belfie13** [comment]
ok sorry i was afk, i'll test asap

**Comment by guiv42** [comment]
No need to be sorry, nothing's urgent ;)

**Comment by belfie13** [comment]
works for me!
