### ISSUE TITLE
feature request: import drums to different strings

### ISSUE THREAD

**Issue by belfie13** [helge17/tuxguitar#222]
to make it easier to view drum tabs, could we import the tab to separate lines similar to the score, at the moment it produces one line and only uses the others if two notes are hit on the same beat.
![Screen Shot 2024-01-21 at 22 58 29](https://github.com/helge17/tuxguitar/assets/39270867/5bb64225-1afa-4006-bf93-3484cef01d88)
2 bars desired output -------> original import last 2 bars

**Comment by guiv42** [comment]
Could you please precise your request?
Lines in a tab represent strings, but for a percussion track, what does a "string" mean?

Intuitively, instead of distributing notes to lines/strings differently, I would rather mask completely the tablature for percussion tracks. Yet I understand these numbers are somehow representative of the instruments played, but I'm not sure at all about this representation: isn't the shape of the note in the score supposed to represent this instrument?

If you think it makes sense to keep 6 "lines/strings", how should notes be distributed on these lines?

**Comment by hubertmeier** [comment]
In my opinion, "notes" like these do not make any sense for the drum track. Perhaps a line for every percussion instrument (which means a lot of lines or only the lines for the used percussion instruments), the note would only show the length of the percussion instrument, the value of the note is not important because every note means another instrument.
Are there percussion instruments with a length? Perhaps only an "x" or something else on the line. Cool would be a font with the real instruments but this is for sure a lot of work.

**Comment by SimplyTheOther** [comment]
Not OP but historically in the Songsterr community, we would format our drums roughly with this string assignment (intended to approximately mimic the drum notation view above):

- Crash cymbals, effect cymbals (china, splash, etc.)
- Hi-hat (open and closed), ride, ride bell
- High-ish toms
- Snare, medium-ish toms
- Low-ish toms (including floor toms)
- Bass drum

If multiple parts of one category were played at once, such as a snare flam, we would split it to adjacent lines, such as the two middle lines for snare flam, two top lines for two crashes, etc. for toms.

For example, here's part of The Final Countdown by Europe as it appears in TuxGuitar:
<img width="669" alt="Screen Shot 2024-01-27 at 12 52 43 am" src="https://github.com/helge17/tuxguitar/assets/19371469/9afc8268-fb7b-46b5-aa99-a08e1d311d86">

Percussion such as cowbell, etc. complicates things a bit more if it is in the same track - I don't think there were any standardised ways of representing it.

I personally think even an "auto-format" percussion to this form would be quite achievable and more useful than nothing.

**Comment by guiv42** [comment]
> could we import the tab to separate lines 

I think I just understood: "import the tab" probably means "import a MIDI file with a percussion track".

I just added a [centralized feature to allocate notes to strings](https://github.com/helge17/tuxguitar/blob/29b27584179efb5dbfacb5e4cc4b20c481647532/common/TuxGuitar-lib/src/org/herac/tuxguitar/song/managers/TGTrackManager.java#L365), this is the one used when MIDI file is imported.
This should be quite easy to implement a variant of this function for percussion tracks, with an arbitrary assignment of percussion instruments to strings, as suggested above.
A possibility could be to store this correspondence in TGDrumMap.java. Just for my curiosity, @SimplyTheOther : are you the [author](https://github.com/helge17/tuxguitar/blob/29b27584179efb5dbfacb5e4cc4b20c481647532/common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/TGDrumMap.java#L7) of this class? (I found some related [history on SF](https://sourceforge.net/p/tuxguitar/patches/37/))

**Comment by belfie13** [comment]
yes i meant staff lines but in tablature they are strings as i dont think there is a standard drum tab format for the tablature view of a drum track. 

Im sure that different symbols are used in music scores but it is common in tablature editors to keep the midi note numbers and split the drum kit components into different tablature lines, as mentioned in a previous comment.

ill try and get the terms correct and be clearer, i was unaware that import could mean something other than the operation in the menu: 'file'->'import ...'. my bad

**Comment by guiv42** [comment]
Distribution to strings as [suggested above](https://github.com/helge17/tuxguitar/issues/222#issuecomment-1912111671) by @SimplyTheOther is now implemented (dd88c008f14138628ce9fcb55b294eca0f973951), it will be available in next pre-release.
I just typed the same "notes" (not the rhythm) of the 2 first bars from your example screenshot in [first message in this discussion](https://github.com/helge17/tuxguitar/issues/222#issue-2092576256), exported song to midi format, then re-imported it so TG allocates the notes to "strings", here is the result:
![result](https://github.com/helge17/tuxguitar/assets/129443524/f23cd2c1-c693-46d0-9262-cbe21c9278c8)

**Comment by belfie13** [comment]
yeah i just tried a couple, majick!!! love it!
