### ISSUE TITLE
Hacks: The Debian version must start with a number

### ISSUE THREAD

**Issue by profOnno** [helge17/tuxguitar#272]
Hacks: The Debian version must start with a number

```
$ sed -i "s/SNAPSHOT/9.99-snapshot/" desktop/build-scripts/tuxguitar-linux-swt-x86_64-deb/src/resources/DEBIAN/control
```

I'm not an hardcore java person. But in my quest to build a development version, I did a quick maven tutorial, and stumbled on how to update the version with `mvn`;
```
 mvn --batch-mode release:update-versions -DdevelopmentVersion=1.6.1-SNAPSHOT
```
Also isn't this the generic way to develop using maven? In the maven `pom.xml` I've seen the version is always have `VERSION-SNAPSHOT` and not just `SNAPSHOT`?

Cheers,

Menno

**Comment by guiv42** [comment]
Hi
I see no reason to change the way the version number is propagated when building a version. We cannot rely on Maven alone to do this job, as the version propagates beyond Maven perimeter (e.g. help pages, tuxguitar.app web site content, Android app).

By the way: constraint to have version name starting with a number only applies if you try to build .deb packages (so: no link with your build issue in #271)

**Comment by guiv42** [comment]
I confirm the occurrence of build warnings, example:
```
[WARNING] Some problems were encountered while building the effective model for org.herac.tuxguitar:tuxguitar:jar:SNAPSHOT
[WARNING] 'version' uses an unsupported snapshot version format, should be '*-SNAPSHOT' instead. @ org.herac.tuxguitar:tuxguitar-pom:SNAPSHOT, /home/guiv/Documents/dev/TuxGuitar/tuxguitar/desktop/pom.xml, line 8, column 11
```

That could be taken care of.
@helge17 : could you please have a look at this? This should have an impact on the global build/delivery script that I cannot test in my environment.

**Comment by helge17** [comment]
If we want to stick strictly to Maven's [guideline](https://maven.apache.org/guides/getting-started/index.html#what-is-a-snapshot-version) for the SNAPSHOT version, we would have to start with version "1.6.2-SNAPSHOT" and change it after each release. Since there are over 100 places where this has to be done every time, I would rather use the pseudo version "9.99-SNAPSHOT" instead. Or do you have any other suggestions?

So I will replace all occurrences of "SNAPSHOT" with "9.99-SNAPSHOT", right? The build warning then disappears.

**Comment by profOnno** [comment]
Not a big fan of that. I'll will try some things and post my findings.

**Comment by profOnno** [comment]
My maven playground:
[https://github.com/profOnno/maven_test](https://github.com/profOnno/maven_test)

I'm still trying to figure out how you do this in the tuxguitar repo

**Comment by profOnno** [comment]
progress... it seems not all. modules have groupId and version tags..

**Comment by helge17** [comment]
At the moment I'm not convinced about using the versions-maven-plugin as suggested in PR #295. The plugin may help for the Maven part, but...

- What about Android (Gradle), Debian control, MacOS Info.plist, the HTML help pages?
- The TuxGuitar version is also hard coded as TGVersion in common/TuxGuitar-lib/src/org/herac/tuxguitar/util/TGVersion.java.
- The versions-maven-plugin is not available as a Debian package, and when building the "official" deb package it is not allowed to download foreign artifacts.

But if it's really that important to set the version to "1.6.2-SNAPSHOT", I'll do it manually and update the version number after each release.

There's a risk that I'll forget or that something goes wrong, but in these cases the versions-maven-plugin won't help either.

**Comment by guiv42** [comment]
> At the moment I'm not convinced about using the versions-maven-plugin

I agree, especially because version name needs to be propagated beyond maven scope (already mentioned [above](https://github.com/helge17/tuxguitar/issues/272#issuecomment-1988187816)).

> But if it's really that important to set the version to "1.6.2-SNAPSHOT", I'll do it manually and update the version number after each release.

I'm definitely no big fan of any manual procedure. Even an automated procedure to edit all these files after each release would also create significant noise in the commits history. Not even mentioning that when one version is released, the name of the following one may not even be known at that time.

My opinion:
If there is a simple way to hide these warnings, then why not: I understand that these warnings may raise questions or concerns from a new developer discovering the build process ("what did I do wrong?").
The suggested "9.99-SNAPSHOT" solution is not completely clean, but I find it simple enough to be seriously considered.

If it becomes too complicated, we could as well document the presence of warnings in "install.md" and/or "contribute.md".

**Comment by helge17** [comment]
Commit [f811c19](https://github.com/helge17/tuxguitar/commit/f811c192ea8b2d3d4f69bdc1875797c0dbd5574f) changes the version from "SNAPSHOT" to "9.99-SNAPSHOT". The Debian version hack is therefore not needed any more, the build warnings have disappeared.

As I said before: If it's really important, I can also switch to "1.6.2-SNAPSHOT". At the moment, I think the effort for this is greater than the benefit.

**Comment by guiv42** [comment]
Shall we close this issue now?
