### ISSUE TITLE
Tracklist/song played measure position scrolling during playback is worse than 1.2

### ISSUE THREAD

**Issue by kainah** [helge17/tuxguitar#28]
I'm sorry if that change of TuxGuitar's behaviour has been discussed earlier, maybe on Sourceforge.
 
When TuxGuitar 1.2's playing position (currently playing measure) in the tracklist gets to the edge of the tracklist area (forwards or backwards), it moves the tracklist horizontally by it's whole width.
However, in the latest snapshot (2023-05-02), and maybe since 1.3 the tracklist scrolls by a single measure forwards or backwards. This is quite uncomfortable if you try to quickly move around the track while playing.
Is there anyone else who also thinks that's a problem?

To be precise, I'm attaching screen captures of 1.2 tracklist behaviour and latest snapshot's one. SWT and JavaFX versions of the new TuxGuitar are identical in that regard.

https://user-images.githubusercontent.com/1732918/236137906-d5aa8a67-f9c4-4f53-8f66-3cb5856fd1e9.mp4

https://user-images.githubusercontent.com/1732918/236137929-30847a7e-1f99-48e2-8613-1916259dee52.mp4

**Comment by guiv42** [comment]
Hi
I agree that scrolling one measure at a time is not very comfortable, because you lose the ability to anticipate.
On the other hand, scrolling the tracks by the whole width is a kind of discontinuous behavior, where you lose instantly all what you could see before it scrolled.
Don't know if what I say is very clear... And thanks @kainah for the short videos, this definitely helps understanding!

What about a possible intermediate behavior, where scrolling could be done by 3/4 of the tracks width? Or [full width minus a few measures]?
In this case, when horizontal scrolling is triggered, the currently playing measure would appear on the left part, but not fully left aligned: the few preceding measures would still be visible.
It could also be possible to trigger the horizontal scrolling a few measures before the edge is reached (still for anticipation)

Note: this proposal only makes sense when scrolling *forward* while playing.
@kainah I do not understand the case you mention moving *backwards*?

**Comment by kainah** [comment]
@guiv42 Yeah, that kind of horizontal scrolling with a few measures "left behind" after scroll would be even better than 1.2! Didn't think of it myself.
And I was wrong about moving backwards. While playing you can use arrow keys to move across measures very fast, that's convenient when you need to re-listen to the same part a lot of times or when you want to move across the playing track to another riff/part/whatever. I didn't check the behaviour of TuxGuitar for moving the measure selection backwards, it's by one measure at a time and it's okay this way. Sorry.

**Comment by guiv42** [comment]
@kainah : I have pushed the modification, so it will be available at next pre-release
(or right now if you want to build from source!)

**Comment by kainah** [comment]
@guiv42 Thanks! I'll close the issue for now.
