### ISSUE TITLE
After new install, cannot find MagicSFver2.sf2

### ISSUE THREAD

**Issue by profOnno** [helge17/tuxguitar#301]
```
./tuxguitar/desktop/build-scripts/tuxguitar-linux-swt-x86_64/target/tuxguitar-SNAPSHOT-linux-swt-x86_64/share/soundfont/MagicSFver2.sf2
./tuxguitar/desktop/TuxGuitar-resources/resources/soundfont/MagicSFver2.sf2
./tuxguitar/desktop/TuxGuitar/share/soundfont/MagicSFver2.sf2
```

It seems the run configuration looks  in `./tuxguitar/desktop/TuxGuitar/share/soundfont/`
which doesn't exist after install. Shouldn't it look in in `target/tuxguitar-SNAPSHOT-linux-swt-x86_64/share/soundfont/`

The other thing I noticed is the 'duplicate?' resource folders.. `TuxGuitar-resources` and `TuxGuitar/share`.
The TuxGuitar-resources only has the `soundfont`.
The TuxGuitar/share has:
```
help
lang
scales
skins
soundfont
templates
tunings
```

**Comment by guiv42** [comment]
Could you please precise what "after new install" means? Which version, how did you install?

It seems you have a problem with parameter tuxguitar.share.path (see [launch script](https://github.com/helge17/tuxguitar/blob/525ac396c195a606059f9cce498bc92bab0b7943/desktop/build-scripts/common-resources/common-linux/tuxguitar.sh#L20)

**Comment by profOnno** [comment]
With 'after a new install` I meant: Delete ~/.m2/repository,  create a new workspace, pull git, install swt, import run configuration.

The problem is that the run configuration seems to cause problems, so my solution is to delete it and re-import it. The not found was caused by the wrong order.. or a git pull... something like that. And I run from eclipse, run button.

So the issue resolved. The question of the 2 places for resources remains.

**Comment by guiv42** [comment]
> The question of the 2 places for resources remains.

It's an issue is your Eclipse configuration. The 2 locations where I can find the soundfont are:
- the "source" folder: `desktop/TuxGuitar-resources/resources/soundfont/`
- the "destination" folder: `desktop/build-scripts/tuxguitar-linux-swt/target/tuxguitar-9.99-SNAPSHOT-linux-swt/share/`

When the app is built, there is a [directive](https://github.com/helge17/tuxguitar/blob/b496941feaf72186faef9cf426531e65afa88543/desktop/build-scripts/tuxguitar-linux-swt/pom.xml#L351) in pom file which copies "source" into "destination".

Then, the app is supposed to be run from "destination" folder. However, by default Eclipse defines parameters of app command line relative to `desktop/TuxGuitar` folder, because it's there it finds the `main()`.
See [this post](https://github.com/helge17/tuxguitar/pull/277#issuecomment-2021520364): you need to redefine `-Dtuxguitar.share.path` command line parameter when launching tuxguitar from Eclipse.

**Comment by profOnno** [comment]
I meant the are two resource folders (source). Soundfont has it's own `TuxGuitar-resourses/soundfont/` and the other resources are stored in   part were the `soundfont` is a resource, and `tuxguitar/TuxGuitar/share` but is maybe that is internal resources.
