### ISSUE TITLE
It's normal that the B (B0) open string for the bass is too low so we can't play it?

### ISSUE THREAD

**Issue by thedoggaming16** [helge17/tuxguitar#313]
It's only a question, and if yes, it's possible to make that we can play it? Or it's too low to make it play ?. Thanks !

**Comment by guiv42** [comment]
No it's not, most probably you have associated the track with an instrument that cannot reach this pitch.
Take care that the 2 settings "tuning" and "instrument" are fully independent. If you chose a "5-string bass" tuning, but your track is associated to a guitar instrument, yes it won't be able to play B0.
See this example video, with these settings I can hear the B0 (with a poor quality, my laptop loudspeakers are not well suited for so low frequencies!)

https://github.com/helge17/tuxguitar/assets/129443524/aceab20b-87c7-4d22-815e-3b6b9bce4a8c

**Comment by thedoggaming16** [comment]
Actually, it's because it's played with the bass instrument (instrument played with a mediator in english???) ans the open B0 string isn't playing. 

https://github.com/helge17/tuxguitar/assets/74026429/7d3e70d7-4aeb-4435-af44-992aa41860f9

**Comment by thedoggaming16** [comment]
I don't know thy the video upload on Githum don't work so there is the same video... but... on youtube: https://www.youtube.com/watch?v=39oqaQtw_3Q

**Comment by guiv42** [comment]
It looks like a limitation of the sound bank. With a "basse électrique jouée au médiator" instrument and version 1.6.1 of TuxGuitar from this repo I cannot hear B0 (C0 is OK).
When I use the 1.6.1 version of TuxGuitar delivered by my Linux distro it's OK. This version uses another soundbank.

**Comment by thedoggaming16** [comment]
So, there is a way to get this soundbank on the 1.6.1 windows version? ?

**Comment by guiv42** [comment]
note: it's OK with 1.6.1 delivered here and "basse électrique jouée au doigt", that could be a short-term solution

**Comment by thedoggaming16** [comment]
And there is any tutorial to how to change the soundfont because I'm bad at informatics and stuff like this. Thanks

**Comment by guiv42** [comment]
don't know... never tried.
One possibility could be to use fluidsynth plugin (?)
- download soundfont file
- menu Tools/Plugins (Outils/greffons in French)
- activate "FluidSynth output plugin", click "configure", then there are controls to add and select new sound fonts: browse to your downloaded file
- then in menu Tools/Settings, "sound" (Outils/Configuration/onglet "son"), "Port Midi": select TG FluidSynth (it should display the name of the selected soundfont)

**Comment by thedoggaming16** [comment]
Okkk thanks !!!!!

**Comment by AndrehMars** [comment]
I use SF2 soundfonts files. It's not the best quality, but it's much better to listen to than the original soundfonts (for Windows), and it's easy to configure
With the source downloaded, I open the track properties, go to the instrument settings and then go to edit MIDI receiver, indicate the path of my SF2 file and voilá.
The problem is that multiple SF2 files do not follow the same instrument order. For example, a guitar-only soundfont might have the distortion sound set to "program 01" instead of "program 30" as is the default. If you are very lucky, there will be a txt file with the order of the sound settings.

It seems like a lot of work, but try installing any VST on TuxGuitar and cry when it fails miserably T.T
TuxGuitar is not a DAW, everything that improves the musician's experience is profit

And, what about TuxGuitar not playing notes below B0, that's entirely the soundfont's fault.

https://github.com/helge17/tuxguitar/assets/165952624/31ea7409-8120-4900-bfb2-3910646b54ea
