### ISSUE TITLE
Bass Guitar is a transposing instrument?

### ISSUE THREAD

**Issue by belfie13** [helge17/tuxguitar#344]
I just found out why Logic writes bass guitars one octave higher, apparently they are a transposing instrument https://en.wikipedia.org/wiki/Transposing_instrument

So bass guitars (and other instruments) are written at concert pitch but they sound 1 octave lower.

I'm not sure if we should do anything about it, unless the majority of other apps do the same then maybe we should?

https://www.logicprohelp.com/forums/topic/94602-logics-default-is-middle-c-as-c3-solved/?do=findComment&comment=536325

**Comment by guiv42** [comment]
It's the same for guitar.

> I'm not sure if we should do anything about it

I don't understand your point.  Since Tux**Guitar** is a guitar-oriented software it just considers this implicitly, but the behavior *is correct*.
For sure if you want to create a piano track in TuxGuitar it will sound 1 octave too low, but as far as I understood it was not Julian's intention to create a general-purpose music software. And I'm perfectly fine with this strategy: keep TuxGuitar as it is, just a *tablature editor*.

If we want to be more rigorous, the only think we could do I think is to show explicitly on the score this 1-octave shift. The usual way to do this is to draw an "eight" digit just below the clef (see [this example](https://github.com/helge17/tuxguitar/issues/169#issuecomment-1971897274)).
If someone understands the [related code](https://github.com/helge17/tuxguitar/blob/218140607f7f2455e1cd61e5a0245db81761665e/common/TuxGuitar-lib/src/org/herac/tuxguitar/graphics/control/painters/TGClefPainter.java#L10)... (I don't)

**Comment by belfie13** [comment]
oh it only matters when importing and exporting other formats and i'm not sure if it does, I can't reproduce the issue
