### ISSUE TITLE
When playback reaches the end of the tab, the cursor goes to the wrong bar if there are repeats in the tab

### ISSUE THREAD

**Issue by buryoutougen** [helge17/tuxguitar#346]
The cursor always jumps back n bars, where n is the number of "extra" bars introduced by the repeats.

**Comment by guiv42** [comment]
Could you please provide a more precise description of your scenario? I can't reproduce.
My test scenario:
- song with 10 bars
- open repeat at bar 7
- close repeat (x1) at bar 8
- click in bar 6
- click play

Expected behavior: TuxGuitar plays bars 6-7-8-7-8-9-10, then cursor jumps back to bar 6 (where it started)
observed behavior: as expected

https://github.com/helge17/tuxguitar/assets/129443524/616d7b05-ba0c-43b6-b96a-1bac46d53ca4

**Comment by buryoutougen** [comment]
Try starting after the repeat (bar 9 or 10 in your example).

**Comment by guiv42** [comment]
OK, so here is the clear description of the problem:
- TuxGuitar 1.6.2 / Linux openSuse tumbleweed
- song with 10 bars
- open repeat at bar 7
- close repeat (x1) at bar 8
- click in bar 9
- click play

Expected behavior: TuxGuitar plays bars 9-10, then cursor jumps back to bar 9 (where it started)
observed behavior: TuxGuitar plays bars 9-10, then cursor jumps back to bar **7**

**Comment by guiv42** [comment]
that should be better now

**Comment by guiv42** [comment]
@buryoutougen : could you please test with latest pre-release ? (>= 2024-04-23)
