### ISSUE TITLE
ubuntu 24.04 dependency update

### ISSUE THREAD

**Issue by cytech** [helge17/tuxguitar#347]
installation failure
ubuntu 24.04 LTS iinstallation requires a debian/control update in deb package
libwebkit2gtk-4.0-37 -> libwebkit2gtk-4.1-0

**Comment by guiv42** [comment]
It's a pity some packages include a version in the package *name*.
Note that this dependency to libwebkit was introduced to fix an Ubuntu-specific issue (#153)

I cannot test currently in an up-to-date Ubuntu environment. Could someone please test the latest pre-release (.tar.gz version), and check if the documentation is correctly displayed? Just start TuxGuitar and type F1: documentation should be displayed in a dedicated TuxGuitar's window.

**Comment by helge17** [comment]
Also under Debian I had to struggle with the dependencies on libwebkit. As far as I had tested, the integrated help viewer (menu Help -> Documentation or F1) only works with libwebkit2gtk-4.0-37, not with libwebkit2gtk-4.1-0. This is why debian/control contains exactly this version.

**Comment by guiv42** [comment]
> the integrated help viewer (menu Help -> Documentation or F1) only works with libwebkit2gtk-4.0-37, not with libwebkit2gtk-4.1-0

This is bad news indeed. Maybe it could be useful to test with a more recent version of SWT?
If Ubuntu forbids browser to access local filesystem (#153) and does not provide the required dependencies to open html files directly in TuxGuitar, I do not see many alternative options. One could be:
- define libwebkit2gtk-4.0-37 as a "recommended" dependency, not mandatory (to avoid blocking installation)
- add a menu item "online help" targeting tuxguitar.app website

**Comment by helge17** [comment]
Some update after my last [test](https://github.com/helge17/tuxguitar/pull/159#issuecomment-1826796815) has apparently enabled the SWT browser to also work with `libwebkit2gtk-4.1-0`. In any case, the local help pages are displayed in Firefox if libwebkit does not work for some reason. I have therefore extended the dependency to `libwebkit2gtk-4.0-37 | libwebkit2gtk-4.1-0` with commit 8a551d5a4cf515eeeb437bff84b7a122ef605104 and moved it to `Recommends` (as @guiv42 already suggested [here](https://github.com/helge17/tuxguitar/pull/159#issuecomment-1826840247), I had overlooked that, sorry). This should cover most use cases and there is already a link to the home page in the menu where you can also find the online help pages. So I would not add a separate link to the online help.

Another option would be to fall back to `https://www.tuxguitar.app/files/<version>/desktop/help/` instead of the local help pages in case of problems with libwebkit. But then the `<version>` has to be set correctly.

**Comment by cytech** [comment]
thank you
i'll try next release

**Comment by guiv42** [comment]
OK, and don't hesitate to re-open issue if needed.
It's available in last pre-release if you want to test now, it's up to you.

**Comment by cytech** [comment]
ubuntu 24.04 LTS
tuxguitar-2024-05-01-master-linux-swt-amd64.deb  installs/upgrades with no problem.
F1 for documentation also works well.
thanx again 
dave
