### ISSUE TITLE
Why the transpose button dissapear

### ISSUE THREAD

**Issue by thedoggaming16** [helge17/tuxguitar#395]
Hello, I'm actually on the 2024-03-28-master and I noticed that the Transposition button got removed

So, I'm asking if it's a bug or it's intentional and if it's intentional why it got deleted. Like I used to uncheck these settings for example: Hearing what Master of Puppets would sound on E# and etc. Thanks

Buttons in question:
![image](https://github.com/helge17/tuxguitar/assets/74026429/f2fb39bf-a9b7-41bf-a91b-ff03c08de267)

**Comment by guiv42** [comment]
Yes it was intentional, see #267 and #209
If you want to change just the pitch when playing, you can use the "offset" field in track tuning dialog.
If you want to transpose song, use dedicated menu "Tools/Transpose", where the different options mentioned in your question above are still present

Trying to handle both actions [change tuning] and [transpose] simultaneously is too complex to handle, in many cases it can lead to inconsistencies.

**Comment by thedoggaming16** [comment]
ah ok thx
