### ISSUE TITLE
Tuxguitar and wayland

### ISSUE THREAD

**Issue by ed57700** [helge17/tuxguitar#438]
Hi dear developer,

I would be glad to see a linux version with wayland support. It only works under X11 which will be retired anytime soon.
I usually work under wayland but have since  to log back in to X11 as the app won't launch under wayland

Thanks for the great Tuxguitar
Kind regards

**Comment by guiv42** [comment]
Hi
which version of TuxGuitar are you using?
This wayland issue should be fixed in 1.6.3 (see #323)

**Comment by ed57700** [comment]
Hi thanks for replying,

I'm using the latest 1.6.3-linux-swt-amd64. I am using a Manjaro plasma based distro (BigLinux)
I'm stuck on a partial screen like below (hope the screenshot displays well)


![Copie d'écran_20240625_131518](https://github.com/helge17/tuxguitar/assets/74775375/e1ffe3c9-3536-4f55-a703-c63fd18786ba)

**Comment by guiv42** [comment]
We cannot say tuxGuitar is not compatible with Wayland, there must be another parameter: I'm using same 1.6.3 version in Linux OpenSuse Tumbleweed / KDE / Wayland without any problem.

This may as well another compatibility issue between Eclipse SWT and Wayland, in the specific context of your distro (?)
Since we have updated SWT again *after* 1.6.3, could you please try the following:
- test with [latest pre-release](https://github.com/helge17/tuxguitar/releases), starting with linux-swt-amd64.tar.gz
- if it still does not work, try version linux-jfx-amd64.tar.gz

**Comment by ed57700** [comment]
Indeed it worked !! Thanks :-)  => with last master linux-swt-amd64.tar.gz from June 23th. The other one jfx did also work (don't know the difference and what it is for?)

Just to mention that I had to install first JRE-OPENJDK (Java 22 full runtime) otherwise tuxguitar would not launch at all (is it mandatory on all linux distro?)

Thanks a lot for your help dear developers, really appreciate ;-)

**Comment by guiv42** [comment]
> It worked !!

Good news :)

> The other one jfx did also work (don't know the difference and what it is for?)

It was a choice of the historical developer to provide several implementations, compatible with diverse user interface frameworks. We maintain both. That could prove useful in case we face a blocking issue one day with one of them.

> I had to install first JRE-OPENJDK (Java 22 full runtime) otherwise tuxguitar would not launch at all (is it mandatory on all linux distro?)

TuxGuitar is a Java application, so it definitely needs a JRE. This dependency is explicit in .deb and .rpm packages, but you need to install it yourself if you use .tar.gz version.

Since your problem seems to be solved, can this issue be closed ?

**Comment by ed57700** [comment]
Thanks a lot guiv42 for your assistance and explanations
I closed this issue
