### ISSUE TITLE
Timing of the silence not refreshed

### ISSUE THREAD

**Issue by Shine753** [helge17/tuxguitar#439]
Using TuxGuitar 1.6.3
When you select a note, the timing of the note is displayed.
When selecting a silence, the timing remains the same and is not refreshed.
![bug](https://github.com/helge17/tuxguitar/assets/37425160/de49f816-a0bd-4c59-9f93-f3d3e9d73de9)

**Comment by guiv42** [comment]
I'm adding a tag "enhancement" here, and not "bug": just reading the code, the observed behaviour is clearly intentional.
When clicking on a beat, Caret duration is only updated if it's not a rest beat:
https://github.com/helge17/tuxguitar/blob/149af1041502c02ee922d613fbca62441ca3103c/desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/component/tab/Caret.java#L262

Need to understand why before trying any modification

**Comment by helge17** [comment]
I think it depends a bit on how you interpret the highlighted note in the duration toolbar: Should it always show the duration of the currently selected note or rest and assume that the note you want to insert at the caret position should have the same duration, as the French translation "Durée de la note ou du silence" suggests? Or should the note you insert next by default have the same duration as the last selected note (most other languages simply use "Duration" as the title for the duration toolbar)?

Anyway, it seems more logical to me that the selected note in the duration toolbar follows the caret, even if you select a rest. So I think your suggestion to change line
`if (this.selectedBeat != null && !this.selectedBeat.getVoice(getVoice()).isRestVoice()) {`
to
`if (this.selectedBeat != null) {`
is a good one. I have tested it and it works perfectly. Just let me know if I should commit it.

**Comment by guiv42** [comment]
Yes I think it can be commited

**Comment by guiv42** [comment]
@Shine753: can we close this issue now?
Implemented since 2024-07-28-master release
