### ISSUE TITLE
When zoomed in line mode when selecting notes program keeps move back to tact 1 + when using scroll it doesnt scroll horizontal

### ISSUE THREAD

**Issue by 666xan666** [helge17/tuxguitar#517]
1. When zoomed in line mode when selecting notes program keeps move back to tact 1. 
2. When you are using horizontal mode mouse scrolls don't scroll horizontally.

**Comment by 666xan666** [comment]
v. 1.6.4 LM 22. Deb package.

**Comment by guiv42** [comment]
> when selecting notes program keeps move back to tact 1

Not understood: what action are you doing, what is the expected behavior? Could you please provide a small video to illustrate your problem?

> mouse scrolls don't scroll horizontally

Let me try to reword, please tell me if I understood correctly:
- type menu View/Page layout, then use mouse wheel: it scrolls vertically, as expected
- type menu View/Linear layout, then use mouse wheel: it still scrolls vertically. In this case, scrolling horizontally would be more appropriate

> v. 1.6.4 LM 22.

What do you mean with "LM 22"?

**Comment by 666xan666** [comment]
ad. 1 - when I am on tact for example 10 and I want to select few notes program automatically moves me back to 1st tact.
ad. 2 - exactly how you wrote.
ad. 3 - LM = Linux Mint 22, kernetl 6.8.0-1013-nvidia-lowlatency

Thank You @guiv42

**Comment by guiv42** [comment]
Thanks for answers 2. and 3.

Sorry, I still don't understand you first problem. Could you please provide a detailed description, step-by-step, of the procedure to reproduce? Precise each menu/button/item you click on, each keystroke, etc. And please use the wording of TuxGuitar English interface (e.g. I don't understand what "tact" means). Better if you can provide a video.
See example below, I tried to enter notes, select notes, zoom in and out, I cannot get anything wrong.

https://github.com/user-attachments/assets/358bc7c2-a379-4f45-96b0-275e6da255ff

**Comment by 666xan666** [comment]
Here it is how it looks like:
https://www.sendspace.com/file/u2fqyr

**Comment by guiv42** [comment]
> Here it is how it looks like: https://www.sendspace.com/file/u2fqyr

I cannot access this link (different errors, including "maintenance in progress try later").
Could you please attach video directly here? Either drag-and-drop as .mp4, or if it doesn't work zip it and drag-and-drop .zip archive.

**Comment by 666xan666** [comment]
https://github.com/user-attachments/assets/5f76d528-2998-4e69-b974-84813c56b945

**Comment by guiv42** [comment]
analysis ongoing: bug introduced by 20ae8bee2671e52678c0372bc076487eb4b3f95f

**Comment by guiv42** [comment]
Two different problems described here:

1. bug: scrolling issue (see videos above)
This should be fixed by #527

2. enhancement request: convert mouse wheel movements to horizontal scrolling instead of vertical scrolling when in linear mode
I understand the proposal, however I'm not so sure it's the best solution. Scrolling vertically can clearly make sense in linear layout, typically for a song with many tracks.

**Comment by guiv42** [comment]
I confirm I prefer not to change the current behavior of mouse wheel in linear mode, for the following reasons:
- vertical scrolling still makes sense when there are many tracks
- horizontal scrolling **is already possible**: some mice include a bi-directional wheel, and it is also possible to swipe horizontally with 2 fingers on a touchpad

So, I suggest closing issue

**Comment by guiv42** [comment]
@666xan666: could you please confirm bug is fixed in latest pre-release? (master branch)

**Comment by 666xan666** [comment]
Can't install it.
Error message: 
"org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."

**Comment by guiv42** [comment]
Please precise which version you are trying to install. Note that the deb package we provide is built for Debian environment. Better use .tar.gz version for other distributions. Also prefer SWT version over JFX.
First pre-release with a fix for this issue is 2024-09-28. So in your case I recommend [tuxguitar-2024-09-28-master-linux-swt-amd64.tar.gz](https://github.com/helge17/tuxguitar/releases/download/2024-09-28-master/tuxguitar-2024-09-28-master-linux-swt-amd64.tar.gz)

**Comment by 666xan666** [comment]
It was installed on LMDE which basically is Debian.

**Comment by guiv42** [comment]
Please manage different issues separately: is this OK with .tar.gz version?

**Comment by guiv42** [comment]
@666xan666 I just see you have edited one comment above, you're not testing the right version
Fix has been implemented in **master** branch, not in **next**
please use [tuxguitar-2024-09-28-master-linux-swt-amd64.tar.gz](https://github.com/helge17/tuxguitar/releases/download/2024-09-28-master/tuxguitar-2024-09-28-master-linux-swt-amd64.tar.gz)

**Comment by guiv42** [comment]
Tested on [2024-09-28 pre-release](https://github.com/helge17/tuxguitar/releases/tag/2024-09-28-master) in **master** branch, SWT version:
- Win10
- Linux openSuse Tumbleweed (.tar.gz)
- Linux Ubuntu 24.04 (.tar.gz and .deb)
- Linux Debian 12.7.0 (.tar.gz and .deb)

Everything's OK.
Can't go any further -> issue closed
