### ISSUE TITLE
Line cut midway

### ISSUE THREAD

**Issue by 10b14224cc** [helge17/tuxguitar#566]
In case of a bend that goes up and down, the line is cut mid-way (only visual artifact, sound is not affected):

![image](https://github.com/user-attachments/assets/b6d6420f-3575-490a-9590-c2ddde0b6856)

**Comment by guiv42** [comment]
That's just because you are using "compact" display mode.
In this mode, only the first movement of a bend is shown to spare horizontal space: e.g. with a bend-release-bend, you can only see the first bend.
So: just click on menu View and uncheck "Compact"
Example with compact mode checked:
![compact](https://github.com/user-attachments/assets/1f6b5634-3e56-458d-b43f-01dee05094c5)
**Without** compact mode:
![NOT_compact](https://github.com/user-attachments/assets/d4c216c4-0783-4842-9707-34508cdfa223)

**Comment by 10b14224cc** [comment]
ok this is how I see it without compact mode

![image](https://github.com/user-attachments/assets/186e7d22-cf4f-4744-a9b1-b8aff1adf733)

(there is no dotted line tough)

thanks

**Comment by guiv42** [comment]
> there is no dotted line on the tab tough

It's normal. On your tablature, the bend movement is split in 2 tied notes:
- one half, bend
- one sixteenth, pre-bend + release

To show explicitly the dotted line, see my screenshot: I have split the bend movement in **3** tied notes:
- one eighth: bend
- one dotted quarter, **hold**: start note with an already bent string, and hold the bend until the end of the note. This displays the dotted line
- one sixteenth, pre-bend + release
