### ISSUE TITLE
BUG: When converting to GP5 file, double dots are changed to dotted

### ISSUE THREAD

**Issue by Sy256** [helge17/tuxguitar#57]
This is not just in this tuxguitar, it also happens in the older 2.0 branched version, https://github.com/pterodactylus42/tuxguitar-2.0beta but since I can't open old 2.0 projects in this newer tuxguitar (it says unsupported version) I had to convert projects to gp5 and found that all double dotted notes get changed to dotted. Any ideas?

**Comment by guiv42** [comment]
No idea, but bug is easy to reproduce and is also present in v1.5.6. Could someone provide a gp5 file generated by GuitarPro (I can't) with a double dotted note?
It would help to identify if bug is linked to gp5 export or import feature (or possibly both?)

**Comment by Sy256** [comment]
Ok so I checked with a friend that's using GP5 and apparently double dotted notes are not a thing in there...so I guess that explains it? Is it possible to fix for tuxguitar though, add it into exports?

**Comment by guiv42** [comment]
OK, so that makes things clear. If GuitarPro doesn't handle double dotted notes, then:
- this issue is *not* a bug of TuxGuitar
- gp5 cannot be a solution to your problem

I understand it's just the consequence of the choice done in 2.0beta fork to change file format in an incompatible manner. If your need is to convert one file created with 2.0beta to a file usable with TuxGuitar from this repo, then from 2.0beta just export with menu "File / Export / Export TuxGuitar 1.5..."
If that's OK for you I would suggest closing this issue, as there is nothing we can do in this repo to solve this.

**Comment by Sy256** [comment]
Ok thanks! I'll use 1.5.6 export instead. Closed
