### ISSUE TITLE
GitHub actions/Workflow enabling

### ISSUE THREAD

**Issue by G-eos** [helge17/tuxguitar#574]
Hello, thanks to have merged GitHub workflow proposal.

I do no see the label into the GitHub interface for your repository (you can see it in the screenshot too) this is just between Pl Requests and Projects for the my fork of your repo.

Can you check if actions are enabled. Please see it in the screenshot on where it has to be enabled:
![image](https://github.com/user-attachments/assets/09e20663-0d63-4fc9-8c6c-65ddf048848e)

No urgency at all, it works on my clone ;-)

Thanks.

**Comment by guiv42** [comment]
Just wondering: is it really needed in *this* repo, since actions are only triggered when pushing, and contributors cannot push directly here?
The most important is to ensure actions are available in contributors' forks, and it seems to be the default (works on my fork also)

**Comment by helge17** [comment]
Just to be sure I understand correctly:

- We keep the actions defined in the `.github` folder in this repo.
- Actions remain disabled in this repository because I don't use the actions yet.
- Anyone who wants to use the Github actions should do so in their fork.

So this issue can be closed, right?

**Comment by G-eos** [comment]
Yes, perfect for me.
