### ISSUE TITLE
Tempo problem on 1.6.5

### ISSUE THREAD

**Issue by ycollet** [helge17/tuxguitar#607]
I am using tuxguitar 1.6.5 on Fedora 41.
After the update to 1.6.5, I removed the configuration file from .config/tuxguitar/
I opened a gp5 score starting with a tempo at 145. 
The first time I play the score, the tempo is at 145.
The second time I play the score; the tempo drops to 120 ...

**Comment by ycollet** [comment]
I am on Linux, using pipewire-jack at 48000 Hz / buffer size 256. Using fluidsynth 2.4.0 + tuxguitar / fluidsynth plugin with the same kind of settings (jack / 48000 / 256) ...

No particular actions between the first and second time.
I just tested with a score at 100, the second time the score was played at 120 too ...

**Comment by guiv42** [comment]
Damn... I can't reproduce. My test scenario:
1. open TG, with default song active, add a few empty measures
2. set tempo to 100 bpm for whole song
3. open player dialog (because it displays the current tempo when playing)
4. hit "play" button on player dialog -> song is played with tempo 100 bpm
5. wait until end of song -> caret returns to measure 1
6. hit play again -> song is played with tempo 100 bpm

also tried to save - close - reopen song, it's always played at 100 bpm

**Comment by ycollet** [comment]
Yes, I haven't this problem with a gp4 file.

**Comment by guiv42** [comment]
but I still can't reproduce with the gp5 file :(

**Comment by ycollet** [comment]
I muted the Rythm guitar. Looks like if the guitar is not muted the problem doesn't occurs

**Comment by guiv42** [comment]
very weird... even with the rhythm guitar muted I still don't reproduce

**Comment by ycollet** [comment]
Ah, excellent ! Thanks for your tests :)

**Comment by guiv42** [comment]
bisecting issue leads to 2b1111ee4267ca9132e36c873eef0ba88d51019c

**Comment by guiv42** [comment]
Thanks for filing this issue!
I hate introducing bugs... too bad no one could see it before 1.6.5 was released

**Comment by guiv42** [comment]
should be ok now

**Comment by guiv42** [comment]
@ycollet : could you please test if it's OK on latest pre-release? (>= 2024-12-17)

**Comment by ycollet** [comment]
Just tested and everything was fine. I close the ticket.
