### ISSUE TITLE
Selcted area cannot be edited if the cursor does not stop on a note

### ISSUE THREAD

**Issue by helge17** [helge17/tuxguitar#68]
If you select an area in the tablature, this area cannot be edited if the cursor is not on a note, because the menu items are disabled.

Cursor on a note:
![grafik](https://github.com/helge17/tuxguitar/assets/5897631/1e1dbe1e-cf39-45e1-a18f-9f65a11a3abf)

Cursor not on a note:
![grafik](https://github.com/helge17/tuxguitar/assets/5897631/1dec969f-573f-4c0c-9fe8-a1fa93218cb1)

**Comment by guiv42** [comment]
Thank you for detecting that issue
Note: it's also present in 2.0beta fork
Fix coming soon

**Comment by guiv42** [comment]
Note: I only have updated the condition to enable/disable "semitone up / down" actions, since only these 2 actions apply to the selection.
For example, it seems correct the "shift up/down" actions remain disabled in the cursor is not on a note, since these actions do not apply to the selection (see #58, implementation of selection-wide actions is in progress). Triggering these actions with no note under the cursor would do nothing.

**Comment by helge17** [comment]
Thanks for the fix!
